FROM quay.io/toolbx-images/alpine-toolbox:edge

LABEL usage="This image is meant to be used with the toolbox command" \
      summary="A cloud-native terminal experience"

COPY extra-packages /
RUN apk update && \
    apk upgrade && \
    grep -v '^#' /extra-packages | xargs apk add
RUN rm /extra-packages